import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service — top3news',
  robots: { index: false, follow: false },
};

export default function TermsPage() {
  return (
    <div className="max-w-2xl mx-auto py-8">
      <h1 className="text-3xl font-black uppercase tracking-tight text-gray-950 mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-400 mb-8">Last updated: June 27, 2026</p>

      <div className="prose prose-sm max-w-none text-gray-700 space-y-6">

        <section>
          <h2 className="text-lg font-black text-gray-900 mb-2">1. Acceptance of Terms</h2>
          <p>By accessing or using top3.news (the "Site"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Site.</p>
        </section>

        <section>
          <h2 className="text-lg font-black text-gray-900 mb-2">2. Description of Service</h2>
          <p>top3news is a news aggregation service that curates and summarizes publicly available news content from third-party sources. We use AI-assisted tools to generate article summaries. The Site is provided for informational purposes only.</p>
        </section>

        <section>
          <h2 className="text-lg font-black text-gray-900 mb-2">3. Intellectual Property</h2>
          <p>All original content on this Site — including the top3news name, logo, pixel art, and AI-generated summaries — is the property of top3news. News articles and content sourced from third parties remain the property of their respective owners. We link to original sources and do not claim ownership of third-party content.</p>
        </section>

        <section>
          <h2 className="text-lg font-black text-gray-900 mb-2">4. Disclaimer of Warranties</h2>
          <p>The Site and its content are provided "as is" without warranties of any kind, express or implied. We do not guarantee the accuracy, completeness, or timeliness of any information on the Site. News summaries generated by AI may contain errors or omissions — always refer to the original source for authoritative information.</p>
        </section>

        <section>
          <h2 className="text-lg font-black text-gray-900 mb-2">5. Limitation of Liability</h2>
          <p>To the fullest extent permitted by law, top3news shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Site or reliance on its content.</p>
        </section>

        <section>
          <h2 className="text-lg font-black text-gray-900 mb-2">6. Third-Party Links</h2>
          <p>The Site contains links to third-party websites. These links are provided for convenience only. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites.</p>
        </section>

        <section>
          <h2 className="text-lg font-black text-gray-900 mb-2">7. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 mt-2 space-y-1">
            <li>Scrape or systematically download content from the Site without permission</li>
            <li>Use the Site for any unlawful purpose</li>
            <li>Attempt to disrupt or interfere with the Site's operation</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-black text-gray-900 mb-2">8. Changes to Terms</h2>
          <p>We reserve the right to modify these Terms at any time. Updated terms will be posted on this page. Continued use of the Site after changes constitutes acceptance of the revised Terms.</p>
        </section>

        <section>
          <h2 className="text-lg font-black text-gray-900 mb-2">9. Governing Law</h2>
          <p>These Terms shall be governed by the laws of the State of Florida, United States, without regard to its conflict of law provisions.</p>
        </section>

        <section>
          <h2 className="text-lg font-black text-gray-900 mb-2">10. Contact</h2>
          <p>For questions about these Terms, contact us at: <a href="mailto:ramonzamora89@gmail.com" className="text-brand hover:underline">ramonzamora89@gmail.com</a></p>
        </section>

      </div>
    </div>
  );
}
